server.port: 7088
spring.application.name: Data Generator
spring.jpa.hibernate.ddl-auto: update
spring.jpa.database-platform: org.hibernate.dialect.PostgreSQLDialect
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring.datasource:
  url: jdbc:postgresql://localhost:5432/test_data?searchpath=basic
  username: postgres
  password: 1qaz2wsXX
  driver-class-name: org.postgresql.Driver
